<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfdg</string>
		<string>context free</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Context Free</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#declaration-shape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declaration-path</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declaration-expr</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#startshape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fields</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#chapter-main</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#chapter-sub</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#controls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#productions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#terminals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pathoperations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cf</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#adjustments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#loop</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#replacement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section-argument</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section-adjustment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section-compound</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>adj-color</key>
		<dict>
			<key>match</key>
			<string>\||\b(h(ue)?|sat(uration)?|b(rightness)?|a(lpha)?)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.adjustment.color.cfdg</string>
		</dict>
		<key>adj-geometry</key>
		<dict>
			<key>match</key>
			<string>\b(x|y|z|s(ize)?|r(ot(ate)?)?|f(lip)?|skew|trans(form)?)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.adjustment.geometry.cfdg</string>
		</dict>
		<key>adj-time</key>
		<dict>
			<key>match</key>
			<string>\||\b((time)scale?)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.adjustment.time.cfdg</string>
		</dict>
		<key>adjustments</key>
		<dict>
			<key>name</key>
			<string>entity.other.attribute-name.adjustment.cfdg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#adj-geometry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#adj-color</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#adj-time</string>
				</dict>
			</array>
		</dict>
		<key>cf</key>
		<dict>
			<key>name</key>
			<string>entity.name.section.cf.cfdg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cf-configuration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cf-symmetry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cf-flag</string>
				</dict>
			</array>
		</dict>
		<key>cf-configuration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cf.prefix.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cf.name.configuration.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CF::)(AllowOverlap|Alpha|Background|BorderDynamic|BorderFixed|Color|ColorDepth|Frame|FrameTime|MaxNatural|MinimumSize|Size|Symmetry|Tile|Time)\b</string>
			<key>name</key>
			<string>entity.name.section.cf.configuration.cfdg</string>
		</dict>
		<key>cf-flag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cf.prefix.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cf.name.flag.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CF::)(Align|ArcCW|ArcLarge|BevelJoin|ButtCap|Continuous|EvenOdd|IsoWidth|MiterJoin|RoundCap|RoundJoin|SquareCap)\b</string>
			<key>name</key>
			<string>entity.name.section.cf.flag.cfdg</string>
		</dict>
		<key>cf-symmetry</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cf.prefix.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cf.name.symmetry.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CF::)(Cyclic|Dihedral|cm|cmm|p3|p3m1|p31m|p6|p6m|pg|pmm|pgg|pmg|pm|p1m1|p2|p2mm|p2mg|p4|p4m|p4g|p11g|p11m)\b</string>
			<key>name</key>
			<string>entity.name.section.cf.symmetry.cfdg</string>
		</dict>
		<key>chapter-main</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.other.chapter.main.name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([ \t]*\*[ \t]*#[ \t]*)([^#\n]*)( [ \t]*#)</string>
			<key>name</key>
			<string>comment.other.chapter.main.cfdg</string>
		</dict>
		<key>chapter-sub</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.other.chapter.sub.name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([ \t]*\*[ \t]*---[ \t]*)([^\n]*)( [ \t]*---)</string>
			<key>name</key>
			<string>comment.other.chapter.sub.cfdg</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.cfdg</string>
								</dict>
							</dict>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>comment.line.number-sign.cfdg</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#fields</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.cfdg</string>
								</dict>
							</dict>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>comment.line.double-slash.cfdg</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#fields</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\*/)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.cfdg</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.cfdg</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#fields</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#chapter-main</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#chapter-sub</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>controls</key>
		<dict>
			<key>match</key>
			<string>\b(loop|if|switch|case|else|finally|transform)\b</string>
			<key>name</key>
			<string>keyword.control.cfdg</string>
		</dict>
		<key>declaration-expr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.declaration-expr.name.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.declaration-expr.params.cfdg</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fields</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z_\-\.\d]*+)\b\s*\(([^\(\)]*+)\)\s*=</string>
			<key>name</key>
			<string>entity.name.section.declaration-expr.cfdg</string>
		</dict>
		<key>declaration-path</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.declaration-prod.type.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.declaration-prod.name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(path)\b\s++([a-zA-Z_][a-zA-Z_\-\.\d]*)</string>
			<key>name</key>
			<string>entity.name.section.declaration-prod.path.cfdg</string>
		</dict>
		<key>declaration-shape</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.declaration-prod.type.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.declaration-prod.name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(shape)\b\s++([a-zA-Z_][a-zA-Z_\-\.\d]*)</string>
			<key>name</key>
			<string>entity.name.section.declaration-prod.shape.cfdg</string>
		</dict>
		<key>directives</key>
		<dict>
			<key>match</key>
			<string>\b(import|startshape)\b</string>
			<key>name</key>
			<string>keyword.other.directive.cfdg</string>
		</dict>
		<key>exp-animation</key>
		<dict>
			<key>match</key>
			<string>\b(frame|ftime)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.animation.cfdg</string>
		</dict>
		<key>exp-binary</key>
		<dict>
			<key>match</key>
			<string>\b(bitand|bitleft|bitnot|bitor|bitright|bitxor)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.binary.cfdg</string>
		</dict>
		<key>exp-constants</key>
		<dict>
			<key>match</key>
			<string>\b(infinity)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.constants.cfdg</string>
		</dict>
		<key>exp-exponential</key>
		<dict>
			<key>match</key>
			<string>\b(exp|log|log10|sqrt)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.exponential.cfdg</string>
		</dict>
		<key>exp-hyperbolic</key>
		<dict>
			<key>match</key>
			<string>\b(acosh|asinh|atanh|cosh|sinh|tanh)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.hyperbolic.cfdg</string>
		</dict>
		<key>exp-integer</key>
		<dict>
			<key>match</key>
			<string>\b(div|divides|factorial|floor|isNatural|mod)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.integer.cfdg</string>
		</dict>
		<key>exp-random</key>
		<dict>
			<key>match</key>
			<string>\b(rand|randint|rand_static)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.random.cfdg</string>
		</dict>
		<key>exp-trigonometry</key>
		<dict>
			<key>match</key>
			<string>\b(acos|asin|atan|atan2|cos|sin|tan)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.trigonometry.cfdg</string>
		</dict>
		<key>exp-value</key>
		<dict>
			<key>match</key>
			<string>\b(abs|if|let|max|min|select|sg)\b</string>
			<key>name</key>
			<string>entity.name.function.expression.value.cfdg</string>
		</dict>
		<key>expressions</key>
		<dict>
			<key>name</key>
			<string>entity.name.function.expression.cfdg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#exp-trigonometry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-hyperbolic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-exponential</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-binary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-random</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-animation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exp-value</string>
				</dict>
			</array>
		</dict>
		<key>fields</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.field.begin.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.field.content.cfdg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.field.end.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(«)([^«»\n]*)(»)</string>
			<key>name</key>
			<string>markup.other.field.cfdg</string>
		</dict>
		<key>import</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.import.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.file-name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(import)\s++(".*"|\S++)</string>
			<key>name</key>
			<string>entity.name.section.import.cfdg</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sign.cfdg</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.integer-float.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\+|\-)?((\d++)?(\.))?\d++\b</string>
			<key>name</key>
			<string>constant.numeric.cfdg</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>(\^|\-|\*|/|\+|\-\-|\.\.|…|\+\-|±|&lt;|&gt;|&lt;=|≤|&gt;=|≥|\=\=|\=|&lt;&gt;|≠|\&amp;\&amp;|\|\||\^\^)</string>
			<key>name</key>
			<string>keyword.operator.cfdg</string>
		</dict>
		<key>pathoperations</key>
		<dict>
			<key>match</key>
			<string>\b(ARCREL|ARCTO|CLOSEPOLY|CURVEREL|CURVETO|FILL|LINEREL|LINETO|MOVEREL|MOVETO|STROKE)\b</string>
			<key>name</key>
			<string>keyword.other.pathoperation.cfdg</string>
		</dict>
		<key>productions</key>
		<dict>
			<key>match</key>
			<string>\b(shape|rule|path)\b</string>
			<key>name</key>
			<string>keyword.other.production.cfdg</string>
		</dict>
		<key>replacement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.replacement.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z_\-\.\d]*+)\s*(\(|\[)</string>
			<key>name</key>
			<string>entity.name.section.replacement.cfdg</string>
		</dict>
		<key>section-adjustment</key>
		<dict>
			<key>name</key>
			<string>entity.name.section.adjustment.unordered.cfdg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.adjustment.unordered.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.adjustment.unordered.end.cfdg</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fields</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#adjustments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>section-argument</key>
		<dict>
			<key>name</key>
			<string>entity.name.section.argument.cfdg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.block.argument.begin.cfdg</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.block.argument.end.cfdg</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fields</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cf</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>section-compound</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.compound.begin.cfdg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.compound.end.cfdg</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.section.compound.cfdg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fields</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#productions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pathoperations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#adjustments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#startshape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#replacement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section-argument</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section-adjustment</string>
				</dict>
			</array>
		</dict>
		<key>startshape</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.startshape.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.startshape.cfdg</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.cfdg</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.production.cfdg</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(startshape)\s++([a-zA-Z_][a-zA-Z_\.\d]*+)((\()(.*?)(\)))*</string>
			<key>name</key>
			<string>entity.name.section.startshape.cfdg</string>
		</dict>
		<key>terminals</key>
		<dict>
			<key>match</key>
			<string>\b(SQUARE|CIRCLE|TRIANGLE)\b</string>
			<key>name</key>
			<string>keyword.other.terminal.cfdg</string>
		</dict>
		<key>types</key>
		<dict>
			<key>match</key>
			<string>\b(number|natural|vector[2-9]|trans)\b</string>
			<key>name</key>
			<string>storage.type.cfdg</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.name.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z_\-\.\d]*+)\s*=</string>
			<key>name</key>
			<string>variable.other.cfdg</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.context-free</string>
	<key>uuid</key>
	<string>8D0EE5A2-FB60-40F8-8D0F-1E1FFB506462</string>
</dict>
</plist>
